version: "3.9"
services:
  app:
    build:
      context: ..
      dockerfile: ./compose/Dockerfile
    ports:
      - "{{HOST_PORT}}:80"
    volumes:
      - ../pack:/var/www/html:ro
{{APP_ENV}}
{{DB_DEPENDS}}
{{MYSQL_SERVICE}}
